/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_movlad_pcl_MyNativeObjectWrapper */

#ifndef _Included_com_movlad_pcl_MyNativeObjectWrapper
#define _Included_com_movlad_pcl_MyNativeObjectWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_movlad_pcl_MyNativeObjectWrapper
 * Method:    alloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_MyNativeObjectWrapper_alloc
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_MyNativeObjectWrapper
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_MyNativeObjectWrapper_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_movlad_pcl_MyNativeObjectWrapper
 * Method:    methodOne
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_movlad_pcl_MyNativeObjectWrapper_methodOne
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
